import os
from langchain_ollama import ChatOllama
from graph.schemas import SupervisorDecision
from graph.state import PatientCareState
from dotenv import load_dotenv
load_dotenv()

# ---------------------------------------------------------
# 1. Define one task generated by the Supervisor
# ---------------------------------------------------------


# ---------------------------------------------------------
# 3. Initialize LLM
# ---------------------------------------------------------

llm = ChatOllama(
    model="llama3.2",
    base_url="http://localhost:11434",  # Connects directly to the hidden running background engine
    temperature=0
)

# Keep the standard json_schema structured configuration active
structured_llm = llm.with_structured_output(
    SupervisorDecision,
    method="json_schema"
)


# ---------------------------------------------------------
# 4. Supervisor prompt
# ---------------------------------------------------------

SUPERVISOR_PROMPT = """
You are the Supervisor Agent in a Patient Care Coordination system.

Your responsibility is ONLY to understand the user's request,
break it into tasks, and route those tasks to the correct
specialist agents.

You must NOT:
- diagnose medical conditions
- recommend treatments
- interpret medical results yourself
- invent patient information
- execute specialist tasks yourself

Available agents:

1. patient_agent

Responsibilities:
- patient profile
- demographics
- medical history
- allergies
- previous visits
- patient timeline
- diagnoses stored in the patient record


2. clinical_agent

Responsibilities:
- lab results
- pending lab tests
- medications
- prescriptions
- refill status
- clinical information retrieval


3. care_management_agent

Responsibilities:
- appointments
- appointment scheduling
- referrals
- referral status
- follow-ups
- care-management activities


ROUTING RULES:

A request may require MULTIPLE agents.

Break complex requests into separate tasks.

Example:

User:
"Show my latest blood test and next cardiology appointment."

Tasks:
- clinical_agent -> Retrieve the patient's latest blood test.
- care_management_agent -> Retrieve the patient's next cardiology appointment.


Another example:

User:
"Show my medical history and current medications."

Tasks:
- patient_agent -> Retrieve the patient's medical history.
- clinical_agent -> Retrieve the patient's current medications.


Do not route to an agent unless it is actually required.

If the request cannot be fulfilled because essential information
is missing, set needs_clarification to true.

Return only the required structured decision.
"""


# ---------------------------------------------------------
# 5. Supervisor Agent
# ---------------------------------------------------------

def supervisor_agent(state: PatientCareState):

    patient_id = state.get("patient_id")
    query = state.get("query", "")

    if not query.strip():
        return {
            "intent": "missing_query",
            "tasks": [],
            "selected_agents": [],
            "needs_clarification": True,
            "clarification_question": "What would you like help with?"
        }

    decision = structured_llm.invoke([
        {
            "role": "system",
            "content": SUPERVISOR_PROMPT
        },
        {
            "role": "user",
            "content": f"""
Patient ID: {patient_id}

User request:
{query}
"""
        }
    ])

    # Remove duplicates while maintaining order
    selected_agents = list(
        dict.fromkeys(task.agent for task in decision.tasks)
    )

    return {
        "intent": decision.intent,
        "tasks": [task.model_dump() for task in decision.tasks],
        "selected_agents": selected_agents,
        "needs_clarification": decision.needs_clarification,
        "clarification_question": decision.clarification_question
    }